# Generated by Django 5.2 on 2025-04-24 00:30

import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='expires_at',
            field=models.DateTimeField(default=listings.models.default_expiry),
        ),
    ]
