# Generated by Django 5.2 on 2025-04-25 04:00

import django.db.models.deletion
import listings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_primary_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(default=listings.models.get_default_owner, on_delete=django.db.models.deletion.CASCADE, related_name='listings_as_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
