# Generated by Django 5.2 on 2025-04-23 18:22

import messaging.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='expires_at',
            field=models.DateTimeField(default=messaging.models.default_expiry),
        ),
    ]
