# Generated by Django 5.2 on 2025-04-24 00:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_alter_listing_expires_at'),
        ('messaging', '0002_message_expires_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='listing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='listings.listing'),
        ),
    ]
