# Generated by Django 5.2 on 2025-04-21 10:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('petrol', 'Benzin'), ('diesel', 'Dizel'), ('hybrid', 'Gibrid'), ('electric', 'Elektro'), ('lpg', 'Gaz')], max_length=10)),
                ('transmission', models.CharField(choices=[('manual', 'Mexanika'), ('automatic', 'Avtomat'), ('semi-auto', 'Yarim avtomat')], max_length=10)),
                ('color', models.CharField(max_length=50)),
                ('mileage', models.PositiveIntegerField()),
                ('engine_size', models.FloatField()),
                ('power', models.PositiveIntegerField()),
                ('drive_type', models.CharField(choices=[('fwd', "Old g'ildirak"), ('rwd', "Orqa g'ildirak"), ('awd', "To'liq g'ildirak"), ('4wd', "4 g'ildirak")], max_length=5)),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('body_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.bodytype')),
                ('features', models.ManyToManyField(blank=True, to='common.feature')),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.make')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.carmodel')),
            ],
        ),
    ]
