# Generated by Django 5.2 on 2025-04-25 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Chevrolet', max_length=100),
            preserve_default=False,
        ),
    ]
