# Generated by Django 5.2 on 2025-04-25 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(default='Chevrolet', max_length=100),
        ),
    ]
