# Generated by Django 5.2 on 2025-04-25 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_remove_car_brand_alter_car_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='engine_size',
            field=models.FloatField(default=2.0),
        ),
    ]
