# Generated by Django 5.2 on 2025-04-25 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_alter_car_engine_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='power',
            field=models.IntegerField(default=100),
        ),
    ]
